// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SendMailStatus int32

const (
	SendMailStatus_MailQueuedSuccess SendMailStatus = 0
	SendMailStatus_MailQueuedFailed  SendMailStatus = 1
)

var SendMailStatus_name = map[int32]string{
	0: "MailQueuedSuccess",
	1: "MailQueuedFailed",
}
var SendMailStatus_value = map[string]int32{
	"MailQueuedSuccess": 0,
	"MailQueuedFailed":  1,
}

func (x SendMailStatus) String() string {
	return proto.EnumName(SendMailStatus_name, int32(x))
}
func (SendMailStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mail_1f3aed1a7aa89c61, []int{0}
}

type SendMailRequest struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMailRequest) Reset()         { *m = SendMailRequest{} }
func (m *SendMailRequest) String() string { return proto.CompactTextString(m) }
func (*SendMailRequest) ProtoMessage()    {}
func (*SendMailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mail_1f3aed1a7aa89c61, []int{0}
}
func (m *SendMailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMailRequest.Unmarshal(m, b)
}
func (m *SendMailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMailRequest.Marshal(b, m, deterministic)
}
func (dst *SendMailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMailRequest.Merge(dst, src)
}
func (m *SendMailRequest) XXX_Size() int {
	return xxx_messageInfo_SendMailRequest.Size(m)
}
func (m *SendMailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMailRequest proto.InternalMessageInfo

func (m *SendMailRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type SendMailResponse struct {
	SendStatus           SendMailStatus `protobuf:"varint,1,opt,name=send_status,json=sendStatus,proto3,enum=api.SendMailStatus" json:"send_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SendMailResponse) Reset()         { *m = SendMailResponse{} }
func (m *SendMailResponse) String() string { return proto.CompactTextString(m) }
func (*SendMailResponse) ProtoMessage()    {}
func (*SendMailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mail_1f3aed1a7aa89c61, []int{1}
}
func (m *SendMailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMailResponse.Unmarshal(m, b)
}
func (m *SendMailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMailResponse.Marshal(b, m, deterministic)
}
func (dst *SendMailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMailResponse.Merge(dst, src)
}
func (m *SendMailResponse) XXX_Size() int {
	return xxx_messageInfo_SendMailResponse.Size(m)
}
func (m *SendMailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMailResponse proto.InternalMessageInfo

func (m *SendMailResponse) GetSendStatus() SendMailStatus {
	if m != nil {
		return m.SendStatus
	}
	return SendMailStatus_MailQueuedSuccess
}

func init() {
	proto.RegisterType((*SendMailRequest)(nil), "api.SendMailRequest")
	proto.RegisterType((*SendMailResponse)(nil), "api.SendMailResponse")
	proto.RegisterEnum("api.SendMailStatus", SendMailStatus_name, SendMailStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MailServiceClient is the client API for MailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailServiceClient interface {
	SendMail(ctx context.Context, in *SendMailRequest, opts ...grpc.CallOption) (*SendMailResponse, error)
}

type mailServiceClient struct {
	cc *grpc.ClientConn
}

func NewMailServiceClient(cc *grpc.ClientConn) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) SendMail(ctx context.Context, in *SendMailRequest, opts ...grpc.CallOption) (*SendMailResponse, error) {
	out := new(SendMailResponse)
	err := c.cc.Invoke(ctx, "/api.MailService/SendMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServiceServer is the server API for MailService service.
type MailServiceServer interface {
	SendMail(context.Context, *SendMailRequest) (*SendMailResponse, error)
}

func RegisterMailServiceServer(s *grpc.Server, srv MailServiceServer) {
	s.RegisterService(&_MailService_serviceDesc, srv)
}

func _MailService_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MailService/SendMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendMail(ctx, req.(*SendMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMail",
			Handler:    _MailService_SendMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}

func init() { proto.RegisterFile("mail.proto", fileDescriptor_mail_1f3aed1a7aa89c61) }

var fileDescriptor_mail_1f3aed1a7aa89c61 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0xcc, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x52, 0xe5, 0xe2, 0x0f,
	0x4e, 0xcd, 0x4b, 0xf1, 0x4d, 0xcc, 0xcc, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12,
	0xe2, 0x62, 0x49, 0xca, 0x4f, 0xa9, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95,
	0x3c, 0xb8, 0x04, 0x10, 0xca, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x4c, 0xb8, 0xb8, 0x8b,
	0x53, 0xf3, 0x52, 0xe2, 0x8b, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0xc1, 0xca, 0xf9, 0x8c, 0x84, 0xf5,
	0x12, 0x0b, 0x32, 0xf5, 0x60, 0x6a, 0x83, 0xc1, 0x52, 0x41, 0x5c, 0x20, 0x75, 0x10, 0xb6, 0x96,
	0x2d, 0x17, 0x1f, 0xaa, 0xac, 0x90, 0x28, 0x97, 0x20, 0x88, 0x17, 0x58, 0x9a, 0x5a, 0x9a, 0x9a,
	0x12, 0x5c, 0x9a, 0x9c, 0x9c, 0x5a, 0x5c, 0x2c, 0xc0, 0x20, 0x24, 0xc2, 0x25, 0x80, 0x10, 0x76,
	0x4b, 0xcc, 0xcc, 0x49, 0x4d, 0x11, 0x60, 0x34, 0xf2, 0xe0, 0xe2, 0x06, 0x6b, 0x4d, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x15, 0xb2, 0xe4, 0xe2, 0x80, 0x99, 0x26, 0x24, 0x82, 0x62, 0x35, 0xd4, 0x37,
	0x52, 0xa2, 0x68, 0xa2, 0x10, 0xc7, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0x43, 0xc1, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xff, 0xf0, 0x9e, 0xc2, 0x13, 0x01, 0x00, 0x00,
}
